"""add desktop_scores json to audit

Revision ID: efa8903bce8a
Revises: 94f54c3c8e82
Create Date: 2026-04-21 10:39:03.900713
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efa8903bce8a'
down_revision: Union[str, None] = '94f54c3c8e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('desktop_scores', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audits', 'desktop_scores')
    # ### end Alembic commands ###
